domain_path: C:\projects\Elbert_S7\SD_card\viti_unified\SD_test\export\SD_test\sw\standalone_microblaze_0
app_src_dir: C:\Xilinx\Vitis\2024.1\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
